# Generated by Django 3.2.4 on 2024-08-07 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20240806_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='costumer_name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='contactform',
            name='contact_form_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
